trainer:
  max_epochs: 150
  precision: bf16-mixed  # TODO: LOOK!! Potential source of error

model:
  lr: 0.001 
  beta_start: 0.0001 
  beta_end: 0.02
  n_diffusion_timesteps: 300
  gap_size: 5
  type_masking: 'continued' # Options are continued or spread

data:
  data_dir: /proj/diffusion-inbetweening/data
  batch_size: 8
  window: 50
  offset: 20